export const AssetType = {
	HALL: 1,
	GAME: 2,
}

export const BoxType = {
	Unity: 1,
	Normal: 2,
	Battle: 3,
}

export const Battle = {
	TableRemoved: "STATE:TABLE:REMOVED",
	TableCreated: "STATE:TABLE:CREATED",
	TableChanged: "STATE:TABLE:CHANGED",
}

export const WoodenFish = {
	CLICK: "click",
	LOADING: "GLOBAL:LOADING",
	LOADED: "GLOBAL:LOADED",
	BLOCKING_LOADING: "GLOBAL:BLOCKING_LOADING",
	BLOCKING_LOADED: "GLOBAL:BLOCKING_LOADED",
	HOME_PRIMARY_PAGES_DIRTY: "HOME:PRIMARY_PAGES_DIRTY",
	HOME_PRIMARY_PAGES_REFRESH: "HOME:PRIMARY_PAGES_REFRESH",
	HOME_OPEN_GAME_BY_CODE: "HOME:OPEN_GAME_BY_CODE",
	SPIN_ACTIVITY_SPIN_COUNT_CHANGED: "SPIN_ACTIVITY:SPIN_COUNT_CHANGED",
}
